tomusborne/generateblocks

includes/class-enqueue-css.php

The AMP plugin inlines all CSS into the `style[amp-custom]` element. External stylesheets referenced by `link` elements get fetched and are then processed (minification and tree shaking). Having them be inline from the start avoids the need to fetch them from the filesystem (or worse) over HTTP.

Always inline CSS on AMP pages to avoid needing to fetch

---

includes/functions.php

Right now there is a memory leak that happens if a user adds a reusable block inside of itself. This PR prevents that leak from happening by adding the reusable block ID into an array and checking against that array before parsing reusable blocks.

Prevent memory leak when reusable block is inside itself

---

includes/general.php

In the WP 5.8 widget area, GB blocks are uncategorized as WP introduced a new filter and didn't add backwards-compatibility in the widget area (guessing): https://www.screencast.com/t/fiy3Ugzln
This should fix that issue while maintaining compatibility with versions prior to 5.8.

Fix block categories in WP 5.8

---

includes/class-enqueue-css.php
includes/functions.php
includes/general.php

Original pull here: https://github.com/tomusborne/generateblocks/pull/63
Now going to merge this into 1.3.4 as a patch release for WP 5.8.
One issue with this PR is that it uses wp_get_sidebars_widgets(), which is private: https://developer.wordpress.org/reference/functions/wp_get_sidebars_widgets/
I'm not sure why, exactly. I suppose we could extract the parts we need and ditch the function.

Style our blocks in the widget areas

---

includes/functions.php

This removes the relative protocol from the Google fonts API request: https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/

Add protocol to Google fonts request

---

includes/class-rest.php

Closes #181
This fixes an undefined index error when saving our options for the first time.
To test, delete the `generateblocks` option from `wp_options` and then click the Save button in the GB settings area.

Fix undefined option when saving settings

---

includes/class-render-blocks.php
includes/general.php
readme.txt

This PR fixes an issue where we lose all block styling in the editor using Firefox when in Tablet or Mobile modes.

Fix missing editor styles in Firefox

---

includes/class-render-blocks.php
package.json
plugin.php
readme.txt

This update fixes an issue in the editor where the GB styles are missing in tablet/mobile modes when using Firefox.
It's scheduled to be released on February 8.

Release 1.4.2

---

includes/general.php

This fixes an issue where content nested in Container blocks aren't added to the post excerpt in archives.
To test, create a new Post with this structure:
Container
--- Container
------ Paragraph
Publish, and view the archives. Without this PR, the paragraph will not be added to the excerpt.

Fix nested block post excerpts

---

includes/class-dynamic-content.php

This fixes a bug where the "Single post" dynamic link option links to the single attachment page for the image instead of the single post when "Featured image" is set as the content type.

Fix dynamic links for featured images

---

includes/class-dynamic-content.php

Closes #302 
This adds the `gb-image-xx` class to the avatar so our styling applies to it.

Fix avatar class

---

includes/class-render-blocks.php

Closes #303 
This fixes a bug where icons added to the right of the button text remained on the left on the frontend when using dynamic buttons.

Fix dynamic button icon location

---

includes/class-dynamic-content.php
includes/class-render-blocks.php

This PR fixes a bug where the dynamic image link was being removed before output.
This moves the function that adds the saved dimensions to the image before we add the link, which prevents it from being stripped.

Fix missing dynamic image link

---

includes/class-render-blocks.php

This makes it so our blocks still display even if the dynamic link returns empty.

Show blocks even if empty dynamic link

---

includes/class-render-blocks.php

This uses the `block.json` file in the `dist` folder to register the image block. This will allow us to exclude the `src` folder from builds in the future if we want to.

Use block.json in dist folder to register

---

includes/class-dynamic-content.php

This PR does two things:
1. It cleans up the dynamic image HTML attributes as `generateblocks_parse_attr()` doesn't remove empty items or trim them. An example is the `id` attribute being printed to the image even when no ID exists.
2. It makes it so our URL-only dynamic image uses the same context name so one filter applies to all dynamic images.

Clean up dynamic image html attributes

---

includes/general.php

This uses the compiled script assets and version instead of defining our own.
I left the old method as a backup just in case.

Use compiled script assets

---

includes/class-render-blocks.php

Closes #463 
This adds a `generateblocks_query_loop_args` so we can filter the frontend query args.

Add generateblocks_query_loop_args filter

---

includes/class-dynamic-content.php

Closes #461 
This PR adds three filters to our dynamic data:
```
generateblocks_dynamic_content_output
generateblocks_dynamic_background_image_url
generateblocks_dynamic_url_output
```
An example of the dynamic content output filter:
add_filter( 'generateblocks_dynamic_content_output', function( $content, $attributes ) {
if ( 'post-date' === $attributes['dynamicContentType'] ) {
$id = GenerateBlocks_Dynamic_Content::get_source_id( $attributes );
return sprintf(
'<time class="entry-date published" datetime="%1$s">%2$s</time>',
esc_attr( get_the_date( 'c', $id ) ),
esc_html( get_the_date( 'l F j, Y', $id ) )
);
}
return $content;
}, 10, 2 );

Add more dynamic content filters

---

includes/class-settings.php

Related: https://github.com/tomusborne/generatepress/pull/372
This encodes the URL to the Customizer.

Encode customizer link

---

includes/class-dynamic-content.php

close https://github.com/tomusborne/generateblocks/issues/482

Fix: Post excerpt not rendered correctly when used inside a GPP block element

---

.github/workflows/assets.yml

This PR changes the actions "Deploy to WordPress.org" and "Plugin asset/readme update" to have manual trigger instead of auto on pushing changes to master/tags.

Change actions trigger from push to manual

---

.github/workflows/build-package.yml
.github/workflows/commit-dist-files.yml
.github/workflows/js-ci.yml

- Fix the JS CI to use cache of node_modules instead of installing dependencies on every action
- Adds manual action to build the GenerateBlocks package
- Adds the action to build dist files on release branches

GitHub actions

---

.github/workflows/build-package.yml
.github/workflows/commit-dist-files.yml
.github/workflows/js-ci.yml
Gruntfile.js
package.json

This PR adds a check to run the action to build dist files only when files inside `src/` directory were changed.
The same was applied to JS CI.

Run commit dist files only on src/ files changes

---

src/blocks/image/components/inspector-controls/ImageSettingsControl.js

This makes it so the Image block alt/title controls only show when in Desktop mode.

Tweak: Only show image alt/title controls for Desktop

---

src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
src/blocks/query-loop/components/utils.js
src/blocks/query-loop/query-parameters.js

This PR does two things:
1. Checks for `-1` as a per_page value to set the `50` cap on posts.
2. Conditionally shows the "Editor only" message if the value is higher than `50`.

Tweak: Improve editor per page cap

---

src/blocks/container/components/InspectorControls.js

close #553 
This fixes an issue where the Container didn't update if it was dragged into or out of a Grid block.

Fix: Update Container type when dragged outside Grid

---

src/extend/dynamic-content/inspector-controls/LinkTypeControl.js

These dynamic link type options don't do anything.

Fix: Remove non-working dynamic link types

---

includes/class-dynamic-content.php
src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
src/extend/dynamic-content/utils/getContent.js

`description` seemed like a very vague option value name. This will break existing Image block captions using the `description` value, but I figure it's best to do this now before things are live.
Not sure it's necessary - open to discussion.

Tweak: Change image description option value name

---

src/blocks/container/css/mobile.js

close #564 
This fixes a block error in the mobile editor when the Container block has a fixed background.

Fix: Block error in editor mobile preview using fixed backgrounds

---

includes/class-render-blocks.php
src/extend/dynamic-content/InspectorControls.js
src/extend/dynamic-content/attributes.js
src/extend/dynamic-content/inspector-controls/LinkTypeControl.js

This PR adds a new toggle when using dynamic links.
It allows you to remove the entire block on the frontend if no dynamic link is found. This is particularly useful for things like next/previous pagination or post meta.

Feature: Add toggle to remove block if no dynamic link

---

src/blocks/headline/css/main.js
src/blocks/headline/css/mobile.js
src/blocks/headline/css/tablet.js
src/components/root-element/index.js

close #570 
This fixes our Headline blocks when set to inline width and in the root.
However, adding Inline Width to the Headline block when it's in the root will prevent it from being centered on the page.
This is also a current bug in the stable version:
It would be nice if we could figure out an actual solution to this bug.

Fix: Inline Headline not inlining in the root

---

src/blocks/query-loop/components/BlockControls.js

This disables the next/previous pagination buttons by default if no link exists.

Tweak: Disable empty next/prev pagination buttons

---

includes/generate-css.php
readme.txt
src/blocks/container/css/main.js

This reverts a change we made where we removed `:visited` selectors from our blocks.
We'll re-visit this in the future with more testing.

Tweak: Re-add :visited selectors

---

src/blocks/container/css/main.js

Blocked by #576 
This fixes a bug where the theme link color (at least in GP) overwrite the Container link color in the editor.

Tweak: Increase Container link specificity in editor

---

src/blocks/grid/block.js
src/blocks/query-loop/components/utils.js
src/components/taxonomies-select/index.js

PR with some quick fixes before releasing
- Change Query loop grid label to "Post template"
- Change Taxonomies select label to "Select terms"
- Fix query loop per page default value of 10

Quick fixes

---

includes/class-render-blocks.php
package.json
plugin.php
readme.txt

Reference https://generatepress.com/forums/topic/site-crashed-after-update-to-generateblocks-pro-12-0/#post-2260533

Bump WP version to 5.9

---

src/blocks/button/components/BlockControls.js

This fixes an issue where the Button `hasUrl` attribute wasn't being set.
Previously, we set this attribute inside the component: https://github.com/tomusborne/generateblocks/blob/1.4.4/src/blocks/button/edit.js#L1123

Fix: Button hasUrl attribute

---

includes/class-query-loop.php

This unsets the correct query arg name for `stickyPosts` where it's set.

Tweak: Unset stickyPosts query arg

---

includes/class-render-blocks.php

close #609 
This resets the postdata by using `wp_reset_postdata()` instead of the method:
https://developer.wordpress.org/reference/functions/wp_reset_postdata/
https://developer.wordpress.org/reference/classes/wp_query/reset_postdata/
I've done some reading and I'm not entirely sure why this is necessary, but core does it here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-template/index.php#L110
Other references:
https://wordpress.stackexchange.com/a/216154
https://developer.wordpress.org/reference/classes/wp_query/#more-information

Fix: Reset the query with wp_reset_postdata

---

includes/class-dynamic-content.php

related to #609 and #610
This fixes the bug described in #609 when a user is using the pagination numbers dynamic data.

Fix: Reset pagination numbers postdata

---

readme.txt
src/blocks/query-loop/components/LoopRenderer.js
src/blocks/query-loop/editor.scss

This fixes a bug where our block toolbars and inspector controls are duplicated (or more) when selecting `a` elements inside the block previews.

Fix: Duplicated block toolbars when selecting links

---

includes/class-render-blocks.php
readme.txt

This fixes the "inherit query" feature so it actually inherits the query.
Previously `$block->context['generateblocks/inheritQuery']` always returned false even if it was toggled.

Fix: Inherit query feature

---

readme.txt
src/blocks/query-loop/components/inspector-controls/parameter-list/index.js

This PR fixes the behavior where query loop parameters were being displayed in the order they were registered in the configuration files. Now we keep the order in which they were added, excluded sticky parameters that still must be displayed at the top of the list.

Fix: Keep the order in which query loop parameter was included

---

includes/class-query-loop.php
readme.txt
src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
src/blocks/query-loop/components/utils.js
src/blocks/query-loop/query-parameters.js

Fix taxonomies/exclude taxonomies parameter to include children terms by default. Also adds a toggle for users to choose what they want.

Fix: Query loop taxonomy query include/exclude children

---

src/components/root-element/index.js

close #656 
This removes the `block-editor-block-list__block` class from our root-element component.
This class is causing conflicts as seen in the linked issue. I believe it likely caused this issue as well: https://secure.helpscout.net/conversation/1981700690/346527?folderId=3610634
This class was added (https://github.com/tomusborne/generateblocks/pull/271) to fix an image floating issue, but it seems removing it doesn't make the bug re-appear.

Tweak: Remove block-editor-block-list__block class from root

---

src/extend/dynamic-content/components/SelectPostType.js

closes #631 
By default we only display post types that have `viewable` set to true, with this filter users can enable any other post type.
Filter usage: 
```js
wp.hooks.addFilter(
'generateblocks.editor.query-loop.enabled-post-types',
'testing-not-viewable-post-types',
function( enabledPostTypes, postTypes ) {
const customPostTypes = postTypes.filter( ( postType ) => ( 'custom-slug' === postType.slug ) );
return enabledPostTypes.concat( customPostTypes );
}
);
```

Feature: Add filter for query loop enabled post types

---

src/blocks/query-loop/components/LayoutSelector.js

This fixes a warning when adding the Query Loop block to the editor.

Fix: Query Loop template key warning

---

src/blocks/container/components/ContainerContentRenderer.js
src/blocks/image/components/ImageContentRenderer.js
src/components/root-element/index.js

close #522 
This should fix an issue in block themes and classic themes using a `theme.json` where the alignwide and alignfull options cause the blocks to lose alignment (and go off screen) in the editor.
It needs to be tested in WP 5.9 and 6.0 with block themes, classic themes and classic themes with theme.json.

Fix: Align classes when using theme.json

---

src/extend/dynamic-content/DynamicRenderer.js

@JeanPaiva This fixes the block error I mentioned earlier.
I also made it check for a valid URL which does two things:
1. Prevents a broken image if the URL isn't an image (wrong URL, Loading text etc...)
2. Prevent the check for the "Loading" string from failing in other languages where the `.includes( 'Loading' )` would no longer work.
Not sure if the valid URL check is a good idea - open to changes there.

Fix broken dynamic image when loading

---

includes/blocks/class-button-container.php
includes/blocks/class-button.php
includes/blocks/class-container.php
includes/blocks/class-grid.php
includes/blocks/class-headline.php
includes/blocks/class-image.php
includes/class-enqueue-css.php
includes/functions.php

This fixes a bug where block CSS was being duplicated when using the External File option in 1.6.

Fix: Duplicate CSS when using external file

---

includes/blocks/class-button-container.php
includes/blocks/class-button.php
includes/blocks/class-container.php
includes/blocks/class-grid.php
includes/blocks/class-headline.php
includes/blocks/class-image.php
includes/class-enqueue-css.php
includes/functions.php

alternative to #682 
#682 works but has an issue where CSS (singular and block-specific) is duplicated when using block themes.
This method works by using `wp_enqueue_scripts` and `wp_add_inline_style` for our inline style. This works because `wp_enqueue_scripts` fires before `wp_head` which is where Slim SEO (in this case) is calling `do_blocks`.
We also have to check `$block_ids` within the `generateblocks_get_dynamic_css` function to prevent duplicate CSS in block themes.
Not sure if this is the best solution.

Fix: Missing CSS when do_blocks is ran early

---

includes/blocks/class-button.php
src/blocks/button-container/block.js
src/blocks/button/attributes.js
src/blocks/button/block.js
src/blocks/button/components/BlockControls.js
src/blocks/button/components/ButtonContentRenderer.js
src/blocks/button/css/main.js
src/blocks/button/css/mobile.js
src/blocks/button/css/tablet.js
src/blocks/button/edit.js
src/blocks/button/editor.scss
src/hoc/withButtonLegacyMigration.js

This allows the Button block to be added outside of the Button Container block.
Buttons within the Button Container will continue to use the `.gb-button-wrapper` selector to maintain backward-compatibility.
Buttons outside of the Button Container only use the `.gb-button` selector.
The only possible "breaking change" here is that the one-time CSS no longer has the wrapper selector.

Feature: Allow Buttons outside of the Button Container block

---

readme.txt
src/components/gradient/index.js

This fixes a bug where if the old opacity slider was set to `0` in the gradient component it wouldn't show and changing the colors wouldn't work as the opacity was set to 0.
This should allow the gradient picker to display the old opacity slider if it's set to `0` so users can set it to `1` and use the newer rgba slider.

Fix: Missing legacy alpha color slider in gradient component

---

includes/blocks/class-grid.php
src/blocks/container/components/InspectorControls.js
src/blocks/grid/css/main.js
src/blocks/grid/css/mobile.js
src/blocks/grid/css/tablet.js
src/blocks/query-loop/components/BlockControls.js
src/hoc/withGridLegacyMigration.js

This PR uses `row-gap` to implement the Vertical Gap option in the Grid block and removes the "Remove Vertical Gap" option from the Container block.

Feature: Remove the "Remove Vertical Gap" option

---

src/blocks/image/components/inspector-controls/ImageSettingsControl.js
src/components/unit-control/index.js

This makes it so we don't have to pass all `props` to the `UnitControl` component.

Tweak: Remove ...props from UnitControl

---

src/blocks/container/components/InspectorAdvancedControls.js
src/blocks/container/components/InspectorControls.js
src/blocks/container/components/TagName.js
src/blocks/container/edit.js

This moves the Container tagName option to the Advanced panel.
It also removes the `containerAfterElementTag` filter as we're not using it.

Tweak: Move tagName option to Advanced

---

src/blocks/headline/components/BlockControls.js
src/blocks/headline/edit.js

`text-align` doesn't work when using `display: flex`.

Remove headline alignment options when using flex

---

includes/functions.php
includes/general.php
src/block-context/button.js
src/block-context/container.js
src/block-context/default.js
src/block-context/headline.js
src/extend/inspector-control/controls/layout/attributes.js
src/extend/inspector-control/controls/layout/components/LayoutCSS.js
src/extend/inspector-control/controls/layout/components/editor.scss
src/extend/inspector-control/controls/layout/index.js

This adds `column-gap` and `row-gap` options to the Container, Button and Headline blocks.

Feature: Add gap options to our blocks

---

src/blocks/button/components/BlockControls.js
src/blocks/container/variations/button-container/index.js

This removes the Button Container variant from the inserter and adds it to the toolbar for the Button blocks.
You can select one or multiple Button blocks and click the button to add them to a Button Container.

Feature: Move Button Container option to toolbar

---

src/shared/editor.scss

This makes the panel icons the same color as the text.

Tweak: Change panel icon color

---

includes/defaults.php
src/blocks/button/edit.js

There's no need to set `inline-flex` and other flexbox attributes on newly inserted buttons.
Instead, let's just set `inline-block` unless another `display` exists (from a template, for example).
`inline-flex` and `align-items: center` should still be set automatically when a user adds an icon.

Tweak: Simplify button layout when inserted

---

src/components/unit-control/index.js

This improves the logic of the `UnitControl` component when splitting numbers and units so we can accept values like `calc()`.

Tweak: Improve logic of UnitControl split

---

src/extend/inspector-control/controls/responsive-tabs/editor.scss

This removes the block description from the inspector controls to free up a little vertical space.

Tweak: Remove block description from inspector controls

---

src/components/migrate-inner-container/utils.js

This migrates the "Inline post meta items" option in GPP Elements to use our Layout options when we turn off the Inner Container.
Kind of sucks adding GPP stuff into GB. If we want to avoid that we would need to insert a filter here instead. Only issue with that is if the user runs the migration before updating GPP.

Tweak: Migrate GPP Element inline option

---

includes/general.php
src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
src/blocks/query-loop/components/utils.js

This PR adds a filter to control the cap of posts in the editor for the Query Loop block.
Reference: https://community.generateblocks.com/t/query-loop-spiking-cpu/816/6

Add filter to control query loop posts cap in the editor

---

includes/class-dynamic-content.php

close #765 
This prevents a PHP notice when using a dynamic excerpt on a page with no ID.
It also adds a new filter so we can filter the source ID.

Fix: get_the_excerpt notice with no source ID

---

src/blocks/button/components/ButtonContentRenderer.js

The `button` tag name makes it so the `RichText` component doesn't accept spaces.
This returns a `span` if `button` is set as the tag name to prevent this.

Fix: No spaces in RichText using button tag name

---

src/blocks/container/components/BlockAppender.js

close #776 
This fixes #776 by adding our own version of the `ButtonBlockAppender` so we can tweak the `position` of the `Inserter` component.
Not ideal, but seems necessary for now until core fixes that issue.

Fix: Container appender positioning

---

src/extend/inspector-control/controls/sizing/components/Height.js
src/extend/inspector-control/controls/sizing/components/MaxHeight.js
src/extend/inspector-control/controls/sizing/components/MaxWidth.js
src/extend/inspector-control/controls/sizing/components/MinHeight.js
src/extend/inspector-control/controls/sizing/components/MinWidth.js
src/extend/inspector-control/controls/sizing/components/Width.js
src/extend/inspector-control/controls/sizing/index.js

This makes it so all our Sizing controls use the same set of units.
They can also be filtered per-control with the `generateblocks.editor.sizingUnits` filter.

Feature: Make sizing units consistent

---

includes/class-render-blocks.php

WordPress 6.1.0 introduced a new way to include multiple scripts/styles in blocks and deprecated the old way: https://developer.wordpress.org/reference/functions/register_block_type/

Tweak: Use new editor_script/style handles

---

src/blocks/button/css/main.js

This adds the current button color CSS to the editor if the button has the `[data-button-is-current]` attribute. This can be used by accordions and tabs to style the current button.

Tweak: Add current button colors

---

includes/blocks/class-container.php
includes/functions.php
includes/general.php
src/block-context/button.js
src/block-context/container.js
src/block-context/default.js
src/block-context/headline.js
src/blocks/container/css/main.js
src/components/gradient/index.js
src/components/migrate-inner-container/index.js
src/components/migrate-inner-container/utils.js
src/extend/inspector-control/controls/background-panel/components/background-options.js
src/extend/inspector-control/controls/layout/attributes.js
src/extend/inspector-control/controls/layout/components/FlexDirection.js
src/extend/inspector-control/controls/layout/components/LayoutCSS.js
src/extend/inspector-control/controls/layout/components/LayoutControl.js
src/extend/inspector-control/controls/layout/index.js
src/extend/inspector-control/controls/layout/options.js
src/extend/inspector-control/controls/shapes-panel/index.js

This adds position options to our blocks and overflow options to our Container block.
It also adds migration for existing instances of `position` and `overflow` being used by other options.

Feature: Add position and overflow options

---

src/blocks/button/components/ButtonContentRenderer.js
src/blocks/container/components/ContainerContentRenderer.js
src/blocks/container/edit.js
src/blocks/headline/components/HeadlineContentRenderer.js
src/blocks/image/components/ImageContentRenderer.js

This adds a `generateblocks.editor.renderBlock` hook to the Container, Button, Headline and Image blocks.
It allows us to hook into the rendering of these blocks with the available props and ref.

Feature: Add generateblocks.editor.renderBlock hook

---

src/blocks/container/edit.js
src/extend/template-selector/editor.scss
src/extend/template-selector/index.js
src/extend/template-selector/templateContext.js

This adds a system for the template selector, currently enabled for the container block.
Usage:
```js
wp.hooks.addFilter(
'generateblocks.editor.templateContext',
'testing-template-context',
function( context, props ) {
return {
label: 'Label',
instructions: 'Instructions',
templates: [
{
id: 'vertical-tabs',
label: 'Vertical tabs',
icon: getIcon( 'shapes' ),
innerBlocks: [
[ 'generateblocks/headline', {
element: 'h3',
content: 'My vertical template',
} ],
],
},
],
};
}
);
```

Feature: Add template selector system

---

src/blocks/container/editor.scss
src/components/migrate-inner-container/index.js

We'll update this message to include a link to the documentation once we have it.

Add Global Style warning in inner container migration modal

---

src/blocks/button-container/edit.js
src/blocks/button/edit.js
src/blocks/container/edit.js
src/blocks/grid/components/WidthControls.js
src/blocks/grid/edit.js
src/blocks/headline/edit.js
src/blocks/image/edit.js

This adds a generic `generateblocks.editor.settingsPanel` filter to each block. We should use one filter name here as we can target specific blocks using the `name` props.

Add generateblocks.editor.settingsPanel filter

---

includes/blocks/class-container.php
includes/functions.php
includes/general.php
src/block-context/button.js
src/block-context/headline.js
src/blocks/container/attributes.js
src/blocks/container/block-controls.js
src/components/migrate-inner-container/utils.js
src/components/unit-control/editor.scss
src/components/unit-control/index.js
src/dashboard.js
src/extend/inspector-control/controls/sizing/attributes.js
src/extend/inspector-control/controls/sizing/components/MaxWidth.js
src/extend/inspector-control/controls/sizing/components/SizingCSS.js
src/extend/inspector-control/controls/sizing/index.js

close #777 
This PR does a handful of things:
1. It changes the `useGlobalContainerWidth` attribute name to `useGlobalMaxWidth`
2. It moves the "Use global max-width" option into the `max-width` input as a button
3. It fixes a bug where you couldn't update the tablet/mobile max-width if you were using the global max-width on desktop.
4. It uses the global max-width as a placeholder on tablet and mobile if needed
5. It adds the global max-width option to the Button and Headline blocks

Improve global max-width option

---

includes/defaults.php
src/blocks/button/edit.js

This checks to make sure a Button doesn't have a `variantRole` before it adds the default styling when it's inserted.
This allows us to define custom Button styling when adding variations without having them conflict with the default Button styling that happens when they're first inserted.

Tweak: Don't set default button styles when using variant

---

includes/blocks/class-button.php
src/blocks/button/css/main.js

blocked by #784 
This makes it so Button hover colors don't apply to the "current" button class.

Tweak: Ignore button hover colors on current buttons

---

includes/blocks/class-grid.php
src/blocks/grid/attributes.js
src/blocks/grid/css/main.js
src/blocks/grid/css/mobile.js
src/blocks/grid/css/tablet.js
src/components/number-control/index.js
src/hoc/withGridLegacyMigration.js

In #718 we switched the Vertical Gap Grid block option from using `margin-bottom` to `row-gap`.
We included backward-compatibility so this doesn't happen on the frontend until the user loads the page and saves it.
However, there are some instances where users relied on that `margin-bottom` for their layouts (the Relay - Footer pattern in the Library, yellow box). When they go to edit their page now, that margin is removed (and replaced with `row-gap`), which could cause issues for some users.
This PR adds another layer of back-compat by using the `useLegacyRowGap` attribute. This option is turned on when you edit a page with existing Grid blocks.
To remove the legacy gap on old blocks, the user has to focus the Vertical Gap option and it will turn off and use `row-gap` instead.

Tweak: Improve Grid row-gap back-compat

---

src/extend/template-selector/index.js

This allows us to set attributes for the parent template in the selector.

Allow Template Selector to set attributes for parent

---

src/blocks/container/block-controls.js

Hide the `Insert inner container` button when the block is a variation.
Having an empty Accordion shows the button. Tabs would show too but because the template selector is not visible.

Fix: Insert inner container button showing for variations

---

src/blocks/container/editor.scss
src/components/migrate-inner-container/index.js

This attempts to make the inner container migration more clear for users.
Instead of a "Use inner container" toggle, we switch it to "Use legacy layout system":
Inside the popover, we attempt to outline exactly what happens when the migration takes place.
This is the popover when we suggest adding an inner Container block:
This is the popover when we suggest turning on the new layout system without adding an inner Container block:

Tweak: Improve inner container migrate popover

---

includes/general.php

This adds the `a` back to the `.gb-button` selector when it has a URL and is set to be a link.
Removing the `a` from the selector was causing specificity issues with some setups.
`isset( $settings['hasUrl'] ) && ! $settings['hasUrl']`
I don't love using this kind of logic, but it's borrowed from how we did it in 1.6, so it's safer to keep it as is for right now.

Tweak: Add more specificity to button link

---

includes/class-query-loop.php
includes/general.php
src/blocks/query-loop/components/BlockControls.js

Pagination buttons have their text color overwritten by the Content Link color in GP using Customize > Colors > Content.
This makes their selectors more specific to fix that by adding a class to the pagination Container.

Tweak: Make pagination button selectors more specific

---

src/block-context/index.js
src/blocks/button-container/edit.js
src/blocks/button/edit.js
src/blocks/container/edit.js
src/blocks/grid/edit.js
src/blocks/headline/edit.js
src/blocks/image/edit.js
src/hoc/index.js
src/hoc/withDeviceType.js
src/hooks/useDeviceType.js
src/utils/get-device-type/index.js

This fixes a regression introduced in #835 where the controls for the selected device wouldn't switch.

Fix: Device switching

---

includes/general.php

This somewhat reverts #826 
The logic we were using feels backward because the Button block used to always be a link. When we added the ability for it to be a span, we adjusted the selector to remove the `a` from the selector.
This PR uses the old logic as it was for old versions of the Button block being used.
Once the block is updated to the latest version, it uses better logic to add the `a` if needed.
It also fixes a bug where dynamic links didn't have the `a` added to the selector.

Tweak: Improve Button selector specificity

---

src/blocks/image/css/main.js
src/extend/inspector-control/controls/sizing/components/SizingCSS.js

close #813 
Previously, we used to have this CSS to prevent blocks inside of our Containers from having `max-width`:
```
body .gb-container .wp-block {
max-width: none;
}
```
We had to remove this to allow our blocks to have their own `max-width` set.
However, we need to make sure that our blocks unset their `max-width` to prevent the standard WP CSS from applying:
```
html :where(.wp-block) {
max-width: 840px;
margin-top: 28px;
margin-bottom: 28px;
}
```
We can overwrite this core CSS because we have a `gb-is-root-block` div surrounding our root blocks which the above CSS will apply to.

Fix: Block max-width

---

includes/functions.php
readme.txt

This allows us to add "0" as an HTML attribute. For example: `tabindex="0"`

Tweak: Allow 0 as HTML attribute

---

src/blocks/container/components/ContainerContentRenderer.js

When adding a pseudo-element background image to an empty Container, our `visual-guidelines` class set the `:before` opacity to `0.2`, causing the background image to fade out.
We don't need visual guidelines in a background image exists.

Tweak: Prevent faded background image in editor

---

src/components/migrate-inner-container/utils.js

We're currently bringing all `sizing` attributes from the surrounding Container block into the inner Container block. The inner Container block only needs `max-width`.

Tweak: Don't apply sizing to inner Container

---

src/components/migrate-inner-container/index.js
src/components/migrate-inner-container/utils.js

This fixes a bug where re-usable blocks inside of a non-reusable Container lose their content during migration:
https://user-images.githubusercontent.com/20714883/212759214-50ccc752-2c54-4788-bd5c-c92a543bcd70.mp4
Gutenberg has a different reason for doing the same thing: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/transforms.js#L27

Fix: Re-usable content removed during Container migration

---

includes/general.php

Battling with theme CSS specificity is hard.
This PR adds (back) the Headline tagname to the CSS selector, and adds the `button` tagname to the Button block when it's set to display as a `<button>`.

Tweak: Add tag name selectors to Headlines and Buttons

---

src/blocks/headline/css/mobile.js
src/blocks/headline/css/tablet.js

Headline spacing options weren't working on tablet/mobile in the editor.

Fix: Headline device spacing in editor

---

src/extend/inspector-control/controls/shapes-panel/index.js
src/extend/inspector-control/index.js

close #888 
This exposes device-specific shape options in the "Tablet" and "Mobile" previews.

Fix: Show device-specific shape panel options

---

includes/class-dynamic-content.php
readme.txt

Not super comfortable with this fix. As it's such an obscure bug I think we can look at it in 1.8 as we'll be revamping dynamic data anyways.

Revert: Triple captions using static image with dynamic link

---

readme.txt
src/hoc/withContainerLegacyMigration.js

This fixes a bug where old Container blocks using the 50% default for grid items weren't migrating to the new `sizing` object. 
To replicate the bug:
1. Use GB 1.3.5
2. Add Grid to page, keep items at 50% (and some at other widths)
3. Update to this 1.7, width attributes will be gone

Fix: Migrate Container sizing for old blocks

---

includes/general.php

This causes root containers to break.
How to replicate:
1. With GB and GBP active, add either an accordion or a tab block to the page and click "Got it" on the onboarding popup
2. Save the page, and disable GBP
3. Clear the session storage for the onboarding keys
4. Add a root container

Fix: Onboarding keys registered by GBP weren't optional

---

src/blocks/grid/components/InspectorControls.js
src/blocks/grid/edit.js

close #941 
This removes the outdated help text from the Vertical alignment option and fixes a bug that requires you to click a template twice in the Grid template selector.

Fix: Double-click when selecting Grid template

---

src/extend/block-controls/controls/alignment-matrix-control.js
src/utils/get-unique-block-names/index.js

This sets the `flexDirection` to `row` when using the Alignment Matrix with nothing but the Button block.
This is only necessary if we decide to ditch the Button Container variant.

Tweak: Align buttons in a row using alignment matrix

---

src/blocks/container/block.js
src/blocks/container/components/InspectorAdvancedControls.js
src/blocks/grid/attributes.js
src/blocks/grid/block.js
src/blocks/grid/edit.js
src/blocks/query-loop/attributes.js
src/blocks/query-loop/block.js
src/blocks/query-loop/components/InspectorAdvancedControls.js
src/blocks/query-loop/edit.js
src/extend/inspector-control/controls/block-label/index.js

Add block label to Grid and query loop. Also, it fixes block label control showing for the Post template variant.

Add block label for query loop and grid blocks

---

src/extend/block-controls/controls/alignment-matrix-control.js

Fix matrix alignment for tab buttons and also inline-flex.

Fix: Matrix alignment not working for inline-flex

---

src/blocks/button/block.js
src/blocks/headline/block.js

This uses "Icon" as the list view label for the Button and Headline if "Remove Text" is toggled.

Tweak: Use "Icon" as list view label

---

src/extend/inspector-control/controls/icon/components/icon-padding.js
src/hooks/useDeviceAttributes.js

This fixes some bugs in `setDeviceAttributes` so we can easily add new device attributes to an object.
We just need to pass the object name as the second parameter in `setDeviceAttributes()`:
`setDeviceAttributes( { textAlign: 'center' }, 'typography' )`
Not sure if this means we can ditch the `attributesWithDevice` array, as we can choose to only use `useDeviceAttributes` with attributes that have support for devices. Only issue there is if we're passing a mix of attributes with and without devices.

Fix: Allow objects in useDeviceAttributes

---

src/components/dimensions/editor.scss
src/components/unit-control/editor.scss
src/extend/inspector-control/controls/sizing/index.js
src/utils/get-icon/index.js

This adjusts the style of the unit picker in our `UnitControl` component so it looks consistent across all browsers.
It also fixes a bug in Safari where the "Top" label in Spacing was right up against the input.

Tweak: Clean up `UnitControl` display

---

src/extend/inspector-control/controls/layout/index.js

Fix: Flex icons based on direction in device previews

---

src/blocks/container/editor.scss

This fixes a gap above the Container appender icon when the Container is empty.
It also fixes a bug where the Container icon in the appender wasn't showing up in Safari.

Fix: Container appender icon spacing

---

readme.txt
src/components/unit-control/index.js

This fixes a bug where the current `UnitControl` component sees values like `.9` as a non-numerical value, so it doesn't add the unit to it.

Fix: Use unit in `UnitControl` if value starts with decimal

---

src/hooks/useDeviceType.js

The device buttons are currently broken if you turn off Sync Responsive Previews in "GenerateBlocks > Settings".

Fix: Broken device buttons when sync preview turned off

---

src/components/unit-control/index.js

This fixes cases where the user uses uppercase units which results in values like this: `10PXpx`

Tweak: Force lowercase units in `UnitControl`

---

src/components/dimensions/index.js
src/extend/inspector-control/controls/borders/index.js

This fixes a sizing issue with the buttons when using the latest Gutenberg plugin.

Tweak: Remove `isSmall` from sync buttons

---

readme.txt
src/hoc/migrations/migrateGlobalStyleAttrs.js

This fixes a bug where our migrated Global Style attributes were overriding local attributes in the editor.
Reference: https://generate.support/topic/gb-v-1-8-0-headline-icon-sizing-bug
To reproduce:
1. Create a Global Style in GB 1.7.3.
2. Add a Headline with some padding, icon padding and icon size.
3. Update to 1.8.0 and use this Global Style in the editor.
4. Try changing the local padding, icon padding or icon size.

Fix: Global styles overwriting local attributes

---

includes/general.php
src/extend/inspector-control/controls/sizing/components/SizingCSS.js
src/extend/inspector-control/controls/spacing/components/SpacingCSS.js

Right now we set the `margin` and `max-width` of our blocks if values for those attributes don't exist.
Loading these resets directly in the block CSS makes them very difficult/impossible to overwrite.
This removes the resets from the individual block CSS and loads them in the `block_editor_settings_all` filter so we can overwrite them with other styles if necessary.

Tweak: Load block margin/max-width resets before block CSS

---

.distignore
Gruntfile.js

Ignores the `.nvmrc` file when packaging up our .zip (`Gruntfile.js`) and sending the files to WP.org (`.distignore`).

Chore: Ignore `.nvmrc` from dist

---

src/blocks/button/editor.scss

These properties can be set by the block and don't need to be reset.

Tweak: Remove Button resets

---

src/components/panel-area/index.js
src/extend/inspector-control/controls/background-panel/index.js
src/extend/inspector-control/controls/borders/index.js
src/extend/inspector-control/controls/colors/index.js
src/extend/inspector-control/controls/flex-child-panel/index.js
src/extend/inspector-control/controls/icon/index.js
src/extend/inspector-control/controls/layout/index.js
src/extend/inspector-control/controls/settings-panel/index.js
src/extend/inspector-control/controls/shapes-panel/index.js
src/extend/inspector-control/controls/sizing/index.js
src/extend/inspector-control/controls/spacing/index.js
src/extend/inspector-control/controls/typography/index.js

While testing #1156, I noticed that the "Advanced Backgrounds" feature in GB Pro no longer appear in the "Container" block.
This is due to the re-naming of the panel area filters.
@iansvo Do you see any issues with the following changes? This should maintain backward compatibility, and it doesn't seem to break the indicators at all.
If we need a more generic name for the panels, maybe we should introduce a new `name` prop with the generic name?

Fix: Panel IDs

---

src/blocks/button/editor.scss

The Button block now has core-added margin in the editor due to my changes here: https://github.com/tomusborne/generateblocks/pull/1152
This PR fixes that issue, but removes the `.editor-styles-wrapper` class which should fix the original issue.

Fix: Button margin in the editor

---

src/blocks/pattern-library/components/pattern.js

The conditional `src` loading was causing previews not to load once we switched to loading core patterns.

Fix: Pattern previews not loading

---

src/pattern-library/components/insert-pattern.js
src/pattern-library/components/library-cache.js
src/pattern-library/components/library-layout.js
src/pattern-library/components/library-provider.js
src/pattern-library/components/pattern-details.js
src/pattern-library/components/pattern-list.js
src/pattern-library/components/pattern.js
src/pattern-library/components/required-components.js
src/pattern-library/components/selected-patterns.js

This PR sets the table to allow Global Style imports on an individual basis.
This means if a pattern uses a Global Style, the library will try to import that style as you insert it onto your page.
This is better than the current method, as you only need to import the styles you're going to use. Currently, we require the import of ALL global styles required in a library before you can even start browsing.

Feature: Import pattern styles as needed

---

src/pattern-library/components/library-layout.js
src/pattern-library/components/pattern-details.js
src/pattern-library/components/pattern-list.js
src/pattern-library/components/selected-patterns.js
src/pattern-library/index.js

Alternative to #1175 
https://github.com/tomusborne/generateblocks/assets/20714883/d37d2a4f-3f03-471e-8cc5-c64a875c25be
Did this as a quick alternative to using a portal to insert the Pattern Library block.
This has the advantage of using core features to add the toggle (no portal needed).
However, it has the disadvantage of not being as obvious/visible.
Nice thing here is that if markup changes, the button will remain there and it will open a regular plugin sidebar with a button to open the library.

Feature: Add pattern library to plugin sidebar

---

includes/general.php
package.json
src/editor-sidebar.js
src/editor-sidebar/index.js
src/pattern-library/index.js

This adds a GB sidebar to the editor.
We can put GB-specific features in here like the ability to open the pattern library or global styles sidebar.
https://github.com/tomusborne/generateblocks/assets/20714883/7534a536-be2c-4b72-bb29-2d68d027f3dd

Feature: Add GB editor sidebar

---

src/pattern-library/components/pattern-details.js
src/pattern-library/components/selected-patterns.js

I noticed a bug introduced in #1180 where the `uniqueId` would change after insertion, but the local block styles wouldn't update, as they're memoized.
This PR updates the `uniqueId` attributes before the block is inserted, so things can remain memoized.

Fix: Inserted pattern styles

---

includes/class-query-loop.php
src/blocks/query-loop/components/QueryLoopRenderer.js

closes https://github.com/tomusborne/generateblocks-pro/issues/485
This prevents users without the proper capability from seeing posts with any status other than `publish` in the Query Loop in the editor and frontend.

Security: Add user capability check to Query Loop post status

---

src/editor-sidebar/editor.scss
src/editor-sidebar/index.js

This adds a custom (filterable) header to our editor sidebar.
This allows us to switch it out conditionally.

Tweak: Add custom editor sidebar header

---

src/extend/inspector-control/controls/layout/components/ThemeWidth.js

closes #1089
This fixes a bug where the "Block Alignment" option wasn't showing up when using a block theme.

Fix: Missing block width alignment in block themes

---

src/pattern-library/components/pattern-details.js
src/pattern-library/components/selected-patterns.js
src/pattern-library/utils.js

During testing I noticed that if I add a new paragraph (and have it selected), then open the Pattern Library and insert a pattern, it inserts the pattern after the empty paragraph.
I think it makes more sense to replace the empty paragraph with the inserted pattern.

Fix: Patterns inserting after selected empty paragraph

---

includes/blocks/class-headline.php
includes/general.php

This fixes a bug where the `.gb-highlight` element was getting the default browser yellow background if the user didn't set a text color in the controls.

Fix: `.gb-highlight` class background

---

src/pattern-library/components/pattern-details.js

This decodes special HTML characters in the pattern titles.

Fix: Special characters in pattern titles

---

src/editor-sidebar/index.js

This adds the sidebar panel ID to the sidebar header so it can be easily styled.

Tweak: Add active panel ID to sidebar header

---

src/pattern-library/components/pattern.js

closes https://github.com/tomusborne/generateblocks-pro/issues/603
This removes the individual pattern lazy loading which seems to cause issues in Chrome.
This shouldn't be necessary anymore, as we have infinite scroll set up that only loads x patterns at a time.

Fix: Patterns not loading properly in Chrome

---

src/pattern-library/components/library-layout.js
src/pattern-library/components/pattern-search.js

This fixes a bug where using the search bar in the Patterns modal displays patterns from libraries other than the active one.
To replicate, switch between libraries and use the search.

Fix: Pattern search mixing up active libraries

---

src/pattern-library/components/library-layout.js
src/pattern-library/components/selected-patterns.js

This fixes a bug where the preview pattern feature doesn't work if the pattern isn't in the current list of patterns being displayed.
https://github.com/tomusborne/generateblocks/assets/20714883/374898c7-e56f-4b88-8092-12caf563e82f
This PR disables the button if the preview isn't available. A better solution would be to have the patterns always be available, but I believe this would require a refactor of how we filter the pattern list.

Fix: Broken pattern preview in bulk select mode

---

src/blocks/headline/editor.scss

This fixes a bug in the editor where Headline blocks set to `div` show the default top/bottom editor margin.

Fix: Headline editor margin when set to `div`

---

includes/functions.php
includes/general.php

The new package entries were missing the proper deps list. This retrieves the deps from the package itself to ensure they’re correct.

Bug: Missing script deps for packages

---

src/blocks/headline/editor.scss

Removes extra style that caused the rich-text span to not display inline styles correctly

Fix text-decoration for headings

---

includes/functions.php

Legacy blocks are showing even when using GBP 1.8.0.

Fix: Legacy blocks showing

---

src/blocks/element/components/BlockSettings.jsx
src/blocks/loop-item/components/BlockSettings.jsx
src/blocks/media/components/BlockSettings.jsx
src/blocks/text/components/BlockSettings.jsx

After some discussion, we've decided it's best to remove simple shortcuts from the new blocks, as they add another layer of UI that doesn't add a ton of value.
A shortcut is acceptable when it:
* Targets a non-default selector, saving the user from multiple clicks and knowing which selector to target
* Does something as well as adjust the styles object (add/remove blocks, etc...)

Tweak: Remove simple shortcuts

---

includes/dynamic-tags/class-dynamic-tag-callbacks.php
includes/dynamic-tags/class-register-dynamic-tag.php
src/blocks/query/templates.js
src/dynamic-tags/components/DynamicTagSelect.jsx

Blocked by #1278 
This PR adds a `linkTo` param to the dynamic tags. This allows you to choose whether to automatically link the dynamic text or not.
It also runs all dynamic tag output through a single filter, so users can filter their output based on the tag/options.

Feature: Add `linkTo` feature to dynamic tags

---

includes/general.php

This fixes an issue where the Text block when being used as a heading was losing all margins in the editor.

Fix: Text block editor margins

---

package-lock.json
package.json
src/components/unit-control/index.js

Gutenberg will soon be enforcing `StrictMode`, which breaks out `firstMount` ref pattern.
Using the `useUpdateEffect()` package fixes this issue, and cleans up the codebase/makes the effect more clear as to what it does.

Fix: Update effects

---

includes/dynamic-tags/class-register-dynamic-tag.php
src/dynamic-tags/components/DynamicTagSelect.jsx

By default, a block will not render if the dynamic tag within it returns no value. This is to prevent things like empty `<img>` elements, or text elements.
However, there might be reason to output the block even if a dynamic tag returns empty. For example, if you've added a dynamic tag to the `title` attribute of a block and it returns nothing, you likely still want that block to render.
This PR adds an option when building the dynamic tag to render the block even if the tag returns empty.

Feature: Add option to render block if no dynamic tag value

---

.eslintrc.json
includes/functions.php
includes/general.php
src/blocks/button-container/block.js
src/blocks/button/block.js
src/blocks/container/block.js
src/blocks/grid/block.js
src/blocks/headline/block.js
src/blocks/image/index.js
src/blocks/query-loop/block.js
src/blocks/text/index.js
src/editor/disable-blocks.js
src/editor/disable-legacy-blocks.js
src/editor/index.js

This PR does a handful of things.
1. Version 1 and version 2 blocks will never appear in the editor together. It's a one or the other kind of thing.
2. If you're using GBP and it has a version less than 1.8, version 1 blocks will show.
3. If you're using legacy Global Styles, version 1 blocks will show.
4. You can choose the version to use with a simple filter:
```
add_filter( 'generateblocks_active_block_version', function() {
return 1; // or 2.
} );
```
Using a number for the above filter gives us flexibility in the future if we want to do a version 3.
It also allows users to opt-in to using version 1 for certain projects, which will make sure the v1 blocks continue to display in the inserter, and v2 blocks don't.

Tweak: Add block version filter

---

includes/dynamic-tags/class-dynamic-tag-callbacks.php
includes/dynamic-tags/class-dynamic-tags.php
includes/dynamic-tags/class-register-dynamic-tag.php
src/dynamic-tags/components/DynamicTagModal.jsx
src/dynamic-tags/components/DynamicTagSelect.jsx
src/dynamic-tags/editor.scss
src/hoc/withDynamicTag.js

This PR changes how dynamic tags are formatted.
Before:
`{post_title postId=123|linkTo=post|renderIfEmpty=true}`
Now:
`{post_title id:123|link:post|renderIfEmpty}`
Main differences:
1. We now use a `:` to separate keys and values.
2. We shortened the keys where possible.
3. Keys can have no value when `true` is assumed.
4. Tags that are not registered will not try to replace themselves in the editor.

Refactor: Dynamic tags

---

config/webpack-dependency-extraction.js
package-lock.json
package.json
webpack.config.js

This PR adds a customized version of the DependencyExtractionWebpackPlugin that has a sorted assets array that places all of our plugin specific deps last to ensure they load as expected. 
Includes a bump for the styles-builder to fix an issue with border values

Bug - Fix webpack dep extraction order

---

src/blocks/media/components/BlockSettings.jsx

This fixes a bug where the Media block was getting a new `mediaId` on every mount, causing a "Are you sure you want to leave" browser dialog even when nothing had changed.

Fix: Media block attributes updating on mount

---

src/components/url-controls/URLControls.jsx

When you add `target="_blank"` to any link in Gutenberg, it will automatically add `rel="noopener"` to the tag.
This was causing an invalid block error when you choose to open a new tab on your `a` blocks in v2 blocks, as the save component wasn't matching the edit component.
This PR ensures that we add `rel="noopener"` if `target="_blank"` is present.

Fix: Target and rel bug

---

src/blocks/loop-item/edit.js
src/blocks/looper/edit.js
src/blocks/query-page-numbers/edit.js
src/blocks/query-terms-list/edit.js
src/blocks/query/edit.js
src/blocks/shape/edit.js
src/blocks/text/edit.js

This uses the `withUniqueId` hoc provided in the Block Styles package across all of our new blocks.

Tweak: Use consistent `withUniqueId`

---

src/blocks/media/components/BlockSettings.jsx

This PR uses CSS for the "Width" and "Height" options in the Image block.

Tweak: Use CSS for image width and height

---

src/blocks/media/edit.js

This adds `width` and `height` values to the image wrapper when the image is using `object-fit`.

Tweak: Add dimensions to image wrapper if using objectFit

---

src/utils/getBlockClasses.js

Seems that the `className` attribute is added automatically, so we don't have to.

Fix: Double classes

---

includes/dynamic-tags/class-dynamic-tags.php
includes/dynamic-tags/class-register-dynamic-tag.php
src/blocks/media/components/Image.jsx

If a dynamic tag returns an ID in an image src, we should take that ID and try to get the URL.

Tweak: Handle dynamic IDs as image src

---

includes/dynamic-tags/class-dynamic-tags.php
includes/dynamic-tags/class-register-dynamic-tag.php
src/blocks/media/components/BlockSettings.jsx
src/blocks/media/edit.js
src/blocks/query/templates.js

Instead of relying on JS to add/remove the `data-media-id` attribute when using a dynamic featured image URL, this PR uses PHP to automatically add the data attribute if necessary.

Refactor: Improve media ID extraction

---

src/dynamic-tags/components/DynamicTagBlockToolbar.jsx
src/dynamic-tags/editor.scss

- Sets the content mode to "preview" when inserting a dynamic tag
- Replaces the edit/preview dropdown with two buttons, making it quicker to switch between modes

Tweak: Dynamic tag toolbar UX

---

includes/dynamic-tags/class-register-dynamic-tag.php
src/dynamic-tags/components/DynamicTagSelect.jsx

This PR flips the logic when it comes to dynamic tags that have no value.
By default, all tags are required to have a value. If one of the tags in a block has no value, the entire block will not render.
This can be prevented by adding `required:false` to any non-essential tags.

Tweak: Switch required tag option logic

---

src/blocks/element/components/BlockSettings.jsx
src/blocks/loop-item/block.json
src/blocks/loop-item/components/BlockSettings.jsx
src/blocks/looper/block.json
src/blocks/looper/components/BlockSettings.jsx
src/blocks/media/components/BlockSettings.jsx
src/blocks/query-page-numbers/components/BlockSettings.jsx
src/blocks/query/components/BlockSettings.jsx
src/blocks/shape/components/BlockSettings.jsx
src/blocks/text/components/BlockSettings.jsx
src/components/IdAttributeControl/IdAttributeControl.jsx
src/components/index.js

This PR enables our Looper and Loop Item blocks to be lists.
It also adds an ID attribute control to our blocks.

Feature: Allow list tag names in loops

---

src/blocks/text/edit.js
src/editor/button-link-toolbar.js
src/editor/index.js

This moves the link toolbar for the Button block all the way to the right, so it's more consistent with other link toolbar buttons.

Tweak: Button link toolbar location

---

package-lock.json
package.json
src/components/image-upload/ImageUpload.jsx
src/components/url-controls/URLControls.jsx
src/components/url-controls/editor.scss
src/dynamic-tags/components/DynamicTagModal.jsx

This PR standardizes input heights in the "Settings" panel of our Block Styles.
There was a mix of input heights due to a change WordPress is going to make in the future.
Instead, this PR increases the height of the controls a little across all of our controls.

Tweak: Standardize input heights

---

assets/css/dashboard-global.css
includes/dashboard.php

We have next to no upsell messages in the admin when Pro isn't activated.
This PR adds an "Upgrade" menu item to the GenerateBlocks menu when GB Pro isn't activated.
This can be disabled with a simple filter if needed:
`add_filter( 'generateblocks_show_upgrade_menu', '__return_false' );`

Tweak: Add upgrade menu item

---

includes/dynamic-tags/class-dynamic-tags.php

This fixes a bug where a dynamic tag returning an ID in an image src wouldn't convert it to the URL.

Fix: Dynamic tag returning ID in img src

---

includes/dynamic-tags/class-dynamic-tags.php

We don't want to be running our search/replace on all blocks for performance reasons.
This limits the checks to our new blocks, and users can filter in other blocks if they need.

Tweak: Limit blocks that dynamic tags work in

---

src/dynamic-tags/components/DynamicTagSelect.jsx
src/dynamic-tags/editor.scss

closes #1438 
This fixes a few bugs:
1. Clearing the `linkTo` comboxbox sets it to null, which causes a runtime error.
2. Activating WooCommerce changes the format of `imageSizes`. This PR normalizes the variable.
3. Inputs in the dynamic tag select are all the same height

Fix: Dynamic tag select bugs

---

src/blocks/element/components/BlockSettings.jsx
src/blocks/element/components/InlineBackgroundImage.jsx
src/blocks/loop-item/components/BlockSettings.jsx
src/blocks/looper/components/BlockSettings.jsx
src/blocks/media/components/BlockSettings.jsx
src/blocks/query-page-numbers/components/BlockSettings.jsx
src/blocks/query/components/BlockSettings.jsx
src/blocks/shape/components/BlockSettings.jsx
src/blocks/text/components/BlockSettings.jsx
src/components/image-upload/ImageUpload.jsx
src/components/url-controls/URLControls.jsx

This removes the extra block setting panel labels, so we rely on the actual control labels only.

Tweak: Remove extra block setting labels

---

src/utils/convertLegacyHtmlAttributes.js

closes #1457 
This fixes a bug where the v1 to v2 block transform throws a runtime error if GBP isn't activated.

Fix: Block transform error

---

includes/blocks/class-looper.php

This fixes a Fatal Error if a Looper block is saved without any inner blocks.

Fix: Error when using an empty Looper block

---

package-lock.json
package.json
src/components/block-styles-builder/BlockStylesBuilder.jsx
src/editor/stores.js
src/hoc/withStyles.js
src/hooks/useBlockStyles.js
src/store/block-styles.js

This PR makes it so our local blocks use the `styles` attribute as their styles store, instead of having a separate styles store we have to constantly sync with.
requires https://github.com/EDGE22-Studios/block-styles/pull/9
requires https://github.com/EDGE22-Studios/styles-builder/pull/17

Refactor: Improve how local block styles are set

---

includes/class-meta-handler.php
package-lock.json

Fixes comparison in get_meta that caused lookups to fail if a numeric ID was passed as a string.

Fix meta handler id handling

---

.eslintrc.json
includes/general.php
src/blocks/text/index.js

This filter allows you to do the following:
```
add_filter( 'generateblocks_default_button_attributes', function() {
return [
'globalClasses' => [ 'gbp-button--primary' ],
];
} );
```
This will make it so every "Button" block you add to your website starts off with the global style, and not any local styles.

Add: `generateblocks_default_button_attributes` filter

---

includes/dynamic-tags/class-dynamic-tag-callbacks.php
includes/dynamic-tags/class-dynamic-tags.php
includes/general.php
src/blocks/query/templates.js
src/dynamic-tags/components/DynamicTagSelect.jsx

closes #1505
This PR replaces the `{{published_date}}` and `{{modified_date}}` dynamic tags with a single `{{post_date}}` tag.
This tag can be configured to show the `published`, `modified` or `modifiedOnly`.
It also adds a `dateFormat` input to the UI.

Feature: `{{post_date}}` tag

---

package-lock.json
src/blocks/loop-item/edit.js
src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
src/hoc/withHtmlAttributes.js

This ensures the preview works correctly when a postId isn’t set in the block’s context.

Fix - Query loop preview is broken when not using Post Query

---

includes/dynamic-tags/class-register-dynamic-tag.php

closes #1539 
Our current dynamic tag parser has a flaw that prevents multiple tags from being parsed if one of them has no options, and the other one does.
This PR aims to simplify the parser so that it treats all dynamic tags the same, regardless of whether they have options or not.

Refactor: Dynamic tag parser

---

src/hoc/withHtmlAttributes.js

Related: https://github.com/tomusborne/generateblocks-pro/pull/780

HTML Attributes - allow data-* attributes to have empty values

---

includes/dynamic-tags/class-dynamic-tag-callbacks.php
includes/dynamic-tags/class-dynamic-tags.php
src/dynamic-tags/components/DynamicTagSelect.jsx

Requires https://github.com/EDGE22-Studios/components/pull/13
This allows us to use a `{{media}}` dynamic tag to pull in items from the Media Library.
This can be used to dynamic fetch images, or their captions/alt tags etc...

Feature: Add `media` dynamic tag

---

package-lock.json
package.json

* Opacity is now a UnitControl
* UnitControl - handling for 1 or 0 units
* UnitControl - remembers previous unit if emptied
* UnitControl - disallowed units were not, in fact, disallowed
* Add better unit handling and simplified logic
* Minor parser tweaks to improve perf and simplify logic.

Fix: Unit control improvements

---

src/blocks/text/edit.js

closes https://github.com/tomusborne/generateblocks/issues/1524

Fix: Bug when using `button` as a `RichText` tag

---

src/blocks/looper/components/LoopInnerBlocksRenderer.jsx

Fixes an error in the condition that handles rendering data in the editor. This fixes an error that caused the inspector controls to disappear for all of the innerBlocks of the looper.

Bug - Looper children break when loop data is empty

---

package-lock.json
package.json

Since free doesn't allow for custom at-rules, it doesn't make sense to show the Container Query options.

Tweak: Remove Container Queries in free

---

includes/class-meta-handler.php

This reverts a previous change that was made to accomodate post meta stored in a nested array structure. Upon reflection, I think that we don’t need to support this as a first-party use case and it will complicate everything else to support it in this manner now.

Revert change to meta handler

---

includes/class-meta-handler.php

Before the reverted tweak this was true, but it was accidentally set to false.

Restore original meta-handler single param value

---

src/blocks/media/components/BlockSettings.jsx
src/blocks/query/components/ControlBuilder.jsx

The `<Control>` component can now only be used within the context of the Styles Builder.

Fix: Broken control

---

includes/dynamic-tags/class-dynamic-tags.php

Fixes a deprecated notice.
> PHP Deprecated:  Automatic conversion of false to array is deprecated

Fix: PHP deprecation

---

includes/blocks/class-loop-item.php
includes/blocks/class-looper.php
includes/blocks/class-query-no-results.php
includes/blocks/class-query-page-numbers.php
includes/blocks/class-query.php
includes/dynamic-tags/class-dynamic-tag-callbacks.php
includes/dynamic-tags/class-dynamic-tags.php
src/blocks/element/block.json
src/blocks/loop-item/block.json
src/blocks/looper/block.json
src/blocks/query-no-results/block.json
src/blocks/query-page-numbers/block.json
src/blocks/query/block.json
src/blocks/query/components/QueryInspectorControls.jsx
src/blocks/query/templates.js
src/blocks/text/block.json

closes #1627 
It turns out that combining the use of JS context (provided by `block.json` using a block attribute) and PHP context (provided via the `WP_Block()` class) can result in your values becoming out of sync.
In the referenced issue, the problem was that `queryType` was correct (passed via JS), but `queryData` was a step behind (PHP context).
In this PR, I decided to group all of our PHP context into a single value (`generateblocks/queryData`). This name doesn't conflict with any of the JS context names.
Then, in all of our PHP, I referenced the PHP context instead of using the JS context values.
JS context still exists for the editor, but should no longer be used on the frontend.
Things to test:

Fix: Deeply nested queries

---

package-lock.json
package.json
src/hoc/withStyles.js

This fixes a bug where styles get mixed up among blocks when:
1. In an at-rule.
2. Switching between blocks.
This happens for at-rules and not nested rules because at-rules are also set on render in `useAtRuleEffect`.

Fix: Styles getting mixed up on atRule

---

src/blocks/looper/components/LoopInnerBlocksRenderer.jsx

This selects the Loop Item block when you switch to a different item in the loop to edit.
This prevents some jumpiness in the UI I've noticed when clicking around in the Loop.

Tweak: Select Loop Item on context change

---

includes/blocks/class-looper.php

This fixes a bug where query data wasn't being consistently passed to loop items, resulting in things like post classes not being output etc...

Fix: Pass query data to loop items

---

src/blocks/image/transforms.js

This sets our default width, height and max-width options when transforming a v1 image.

Fix: Image styles on transform

---

includes/dynamic-tags/class-register-dynamic-tag.php

This PR allows our dynamic tag options to end with a space.
For example: `{{terms_list id:12|option:value|sep:, }}`

Fix: Allow trailing dynamic tag spaces

---

includes/dynamic-tags/class-dynamic-tag-callbacks.php

This allows our Next/Previous URL dynamic tags to work even when they don't exist within a Query block.
This is important if they're hooked into a theme-built archive.

Tweak: Allow next/prev posts URLs with no Query

---

includes/dynamic-tags/class-dynamic-tags.php
src/dynamic-tags/utils.js
src/editor/style-html-attribute.js
src/hoc/withDynamicTag.js

related https://github.com/tomusborne/generateblocks/pull/1715
We need to pass the `uniqueId` to the dynamic tag replacement function now.

Fix: Excerpt tag not previewing

---

includes/class-enqueue-css.php
package-lock.json
package.json
src/hoc/withStyles.js

requires https://github.com/EDGE22-Studios/block-styles/pull/18
We convert encoded entities for editor use, and we handle encoded entities that make their way into the saved CSS.

Tweak: Handle HTML entities in styles object

---

src/hoc/withStyles.js

Fixes second part of this issue: https://github.com/tomusborne/generateblocks/issues/1730

Fix: Show correct at-rule style value in block settings

---

package-lock.json
package.json

* Add: Fallback preview support in color picker https://github.com/EDGE22-Studios/styles-builder/pull/72
* Add: Styles indicator to the "More" selectors dropdown https://github.com/EDGE22-Studios/styles-builder/pull/71
* Add: `static` value to the "Position" control https://github.com/EDGE22-Studios/styles-builder/pull/70
* Fix: Inability to type some units to the `UnitControl` https://github.com/EDGE22-Studios/styles-builder/pull/69

Update Styles Builder

---

includes/dynamic-tags/class-dynamic-tags.php

Fix comments count dynamic tag not using custom text for single comment.
The tag callback expects `single` as the option key, but registration used `one`. Updated registration to use correct key name.

fix: update comments count option key to match callback expectation

---

.eslintrc.json
includes/deprecated.php
includes/general.php
src/blocks/looper/components/LoopInnerBlocksRenderer.jsx

This loads our `gbPermissions` object earlier than our other scripts in the editor, so it's readily available.

Tweak: Load permissions earlier in editor

---

includes/functions.php

closes https://github.com/tomusborne/generateblocks-pro/issues/849
WordPress doesn't allow `download` to have a value: https://github.com/WordPress/gutenberg/blob/a579f73cf5e546f3e639b1eae2cef55bf31c6848/packages/blocks/src/api/validation/index.js#L433-L434

Fix: Allow `download` attribute to have a value

---

src/blocks/media/editor.scss

WordPress added `pointer-events: none` to images in the editor as of WP 6.8. This broke our image selection logic in the editor.

Fix: Image selection in WP 6.8

---

src/blocks/element/edit.js
src/blocks/loop-item/edit.js
src/blocks/text/edit.js

This removes the "link" block selectors from the list of selectors when using a block that is already a link.

Tweak: Default block selectors

---

includes/dynamic-tags/class-register-dynamic-tag.php
readme.txt

This fixes a bug where our dynamic tag parsing was searching the full `$content` provided by the block.
This meant that blocks with inner blocks (like the Container) were having their entire content searched for dynamic tags and replaced.
The result of this meant that all HTML inside of a block like the Container was being searched and parsed.
For example, if you add a non-supported block like a Paragraph and give it a dynamic tag and placed it inside a Container, the system would try to parse the tag even though it's not supported in the system. The result would be that the entire Container block would not render if that dynamic tag didn't return a value.
This PR tries to search the HTML of the individual block itself.

Fix: Dynamic tag parsing all content at once

---

includes/functions.php

This ensures block scripts and styles are always enqueued in the `init` hook regardless of whether we're using inline or file CSS.

Fix: Enqueue block scripts always

---

src/blocks/loop-item/components/BlockSettings.jsx

closes https://github.com/tomusborne/generateblocks/issues/1862

Fix: Missing loop item tag name option
