- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/chore.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature.md
> Add GitHub issue templates

- package.json
- plugin.php
- readme.txt
> Prepare for 1.3.4 release

- includes/general.php
> wp-editor should not be enqueued in the new widget editor

- includes/class-enqueue-css.php
> Error when editing widget in the customizer

- package.json
- plugin.php
- readme.txt
> Prepare 1.3.5

- .github/workflows/js-ci.yml
- Gruntfile.js
- package.json
- src/components/unit-picker/test/index.js
This PR adds JS unit tests and the JS CI action.
> Add js unit tests

- package.json
- plugin.php
Update version to 1.4.0-alpha.1
> Bump version

- readme.txt
First draft of changelog. Need to review the commits again to make sure nothing else needs to be added.
> Update changelog for 1.4.0

- package.json
- plugin.php
- readme.txt
> Release 1.4.0 alpha.2

- package.json
- plugin.php
- readme.txt
> Release 1.4.0 beta.1

- package.json
- plugin.php
> 1.4.0-rc.2

- includes/class-query-loop.php
This fixes a bug where the pagination element is misaligned when the grid has horizontal gap added.
This is because the pagination is inside of the grid element which has negative margin applied to it in order to achieve the horizontal gap feature.
Without fix: https://www.screencast.com/t/ro4zfkmqy
With fix: https://www.screencast.com/t/Zq3YNBYuHXw
> Fix pagination alignment

- includes/class-dynamic-content.php
> Fix excerpt not showing with multi query loops in the same page

- includes/class-dynamic-content.php
This fixes a PHP notice when you pull data from a specific post.
> Fix postType notice

- Gruntfile.js
This makes it so our action package and local package actions use the same methods.
> Simplify grunt package

- .github/workflows/php-ci.yml
- composer.json
> Add php ci

- .github/workflows/commit-dist-files.yml
- .github/workflows/js-ci.yml
- .github/workflows/php-ci.yml
> Fix Actions

- includes/class-render-blocks.php
- package.json
- plugin.php
- readme.txt
> Release: 1.5.1

- readme.txt
- src/blocks/container/components/InspectorControls.js
> Fix: Container gridId attribute not updating correctly

- includes/class-query-loop.php
- package-lock.json
- readme.txt
- src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
- src/blocks/query-loop/components/utils.js
- src/blocks/query-loop/query-parameters.js
> Fix: Sticky posts always displaying

- readme.txt
- src/blocks/image/components/ImagePlaceholder.js
- src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
- src/extend/dynamic-content/utils/getContent.js
> Fix: Broken image block when avatars aren't available

- readme.txt
- src/blocks/container/block.js
- src/blocks/grid/block.js
> Tweak: Move Post Template list view label to Container

- readme.txt
- src/blocks/query-loop/components/InspectorControls.js
- src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
- src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
- src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
- src/blocks/query-loop/components/utils.js
- src/blocks/query-loop/query-parameters.js
- src/components/authors-select/index.js
- src/components/post-type-records-select/index.js
- src/components/taxonomies-select/index.js
Adding some filters to facilitate integration with GBP
> Feature: Added filters to integrate related posts

- readme.txt
- src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
- src/blocks/query-loop/components/utils.js
close https://github.com/tomusborne/generateblocks/issues/627
> Fix: Non hierarchical taxonomies with broken REST API calls

- includes/class-query-loop.php
Fix: https://secure.helpscout.net/conversation/1985683091/347207
> Fix: Sticky posts only not displaying correctly in the frontend

- readme.txt
- src/components/icon-picker/index.js
> Fix: Removing icons without text does not display text back again

- src/blocks/headline/transforms.js
> Tweak: Headline transform to core Heading keep the level

- src/components/color-picker/index.js
> Fix: Color picker behavior

- includes/blocks/class-container.php
- src/blocks/container/edit.js
Add an "article" tag to the container.
Reference #665
> Tweak: Add container article tag

- readme.txt
- src/components/color-picker/index.js
Reference: https://edge22studios.slack.com/archives/C022YLCJXHS/p1663025409134349
> Fix: Container styles being overwritten when multi-selected

- includes/blocks/class-button-container.php
- includes/blocks/class-button.php
- includes/blocks/class-container.php
- includes/blocks/class-grid.php
- includes/blocks/class-headline.php
- includes/blocks/class-image.php
- src/blocks/button-container/components/BlockControls.js
- src/blocks/button-container/edit.js
- src/blocks/button/components/BlockControls.js
- src/blocks/button/components/ButtonContentRenderer.js
- src/blocks/button/edit.js
- src/blocks/button/save.js
- src/blocks/container/components/BlockAppender.js
- src/blocks/container/components/ContainerContentRenderer.js
- src/components/icon-picker/index.js
This PR adds filters for our Container and Button appenders.
> Feature: Add block appender filters

- includes/blocks/class-button.php
- includes/blocks/class-headline.php
- includes/class-dynamic-content.php
> Fix: Dynamic content class conflicts

- includes/functions.php
> Fix php 8 deprecation warning

- src/components/unit-control/index.js
This allows us to use non-numerical values in the `UnitControl` component. This will be useful when adding `auto` margins or other string-based values to fields that usually have a numeric value. This will also allow for CSS variables in these fields.
> Feature: Allow non-numerical values in unit control

- src/block-context/grid.js
- src/block-context/index.js
- src/blocks/grid/block.js
- src/blocks/grid/components/InspectorControls.js
- src/blocks/grid/edit.js
- src/hoc/withResponsiveTabs.js
> Grid block controls refactor

- src/block-context/container.js
- src/block-context/default.js
- src/block-context/index.js
- src/blocks/container/block.js
- src/blocks/container/components/InspectorControls.js
- src/blocks/container/edit.js
- src/extend/inspector-control/controls/background-panel/components/attachment.js
- src/extend/inspector-control/controls/background-panel/components/background-color-overlay.js
- src/extend/inspector-control/controls/background-panel/components/background-options.js
- src/extend/inspector-control/controls/background-panel/components/image-opacity.js
- src/extend/inspector-control/controls/background-panel/components/image-size.js
- src/extend/inspector-control/controls/background-panel/components/image-url.js
- src/extend/inspector-control/controls/background-panel/components/position.js
- src/extend/inspector-control/controls/background-panel/components/repeat.js
- src/extend/inspector-control/controls/background-panel/components/selector.js
- src/extend/inspector-control/controls/background-panel/components/size.js
- src/extend/inspector-control/controls/background-panel/components/use-inline-style.js
- src/extend/inspector-control/controls/background-panel/index.js
- src/extend/inspector-control/controls/colors/index.js
- src/extend/inspector-control/controls/shapes-panel/index.js
- src/extend/inspector-control/controls/spacing/components/minimum-height.js
- src/extend/inspector-control/controls/spacing/components/vertical-alignment.js
- src/extend/inspector-control/controls/spacing/components/z-index.js
- src/extend/inspector-control/controls/spacing/index.js
- src/extend/inspector-control/controls/spacing/options.js
- src/extend/inspector-control/index.js
- src/hoc/withResponsiveTabs.js
Refactor Container block inspector controls
> Refactor Container block inspector controls

- includes/blocks/class-button.php
- includes/blocks/class-headline.php
- src/block-context/button.js
- src/block-context/headline.js
- src/blocks/button/css/main.js
- src/blocks/button/css/mobile.js
- src/blocks/button/css/tablet.js
- src/blocks/headline/css/main.js
- src/blocks/headline/css/mobile.js
- src/blocks/headline/css/tablet.js
This adds flex child controls to the Button and Headline blocks.
> Feature: Add flex child controls to Headline and Button blocks

- src/blocks/container/css/main.js
- src/blocks/container/editor.scss
This is an attempt to approve the block appender within the Container block.
The main differences are the design of the button, and the fact it absolutely positions itself if it's within a flex Container. This prevents the button from getting in the way of the flex layout.
> Tweak: Improve Container block appender

- src/blocks/button/components/ButtonContentRenderer.js
> Fix: setAttributes console log warning

- src/blocks/container/edit.js
Fix the container anchor tag not updating correctly.
> Fix container anchor tag

- includes/blocks/class-container.php
> Fix: Container mobile padding

- src/blocks/container/components/ComponentCSS.js
- src/blocks/container/css/main.js
> Fix: Container error when uploading background image

- src/blocks/grid/components/WidthControls.js
- src/blocks/grid/edit.js
This adds width controls in the Block Settings panel for grid item Containers.
> Feature: Add grid item width controls

- src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
- src/blocks/query-loop/query-parameters.js
- src/components/authors-select/index.js
- src/components/post-type-records-select/index.js
- src/components/taxonomies-select/index.js
- src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
> Improve advanced select results

- includes/class-rest.php
- includes/general.php
- src/blocks/container/block-controls.js
- src/components/onboard-popover/index.js
- src/components/onboard-popover/onboards/insert-inner-container-onboard.js
- src/components/onboard-popover/styles.scss
This adds an onboard popover for the Insert inner container toolbar button.
> Feature: Add onboard system

- includes/general.php
- src/block-context/button.js
- src/block-context/headline.js
- src/extend/inspector-control/controls/layout/attributes.js
- src/extend/inspector-control/controls/layout/components/ZIndex.js
- src/extend/inspector-control/controls/layout/index.js
1. Adds z-index options to the Button and Headline blocks
2. Adds responsive z-index options to the Container block when not using an inner container
> Feature: Add more z-index options

- includes/blocks/class-button.php
This adds our `buttonType` option to dynamic Buttons.
> Tweak: Add buttonType support for dynamic buttons

- includes/general.php
Related to https://github.com/tomusborne/generateblocks-pro/issues/195
> Feat: Add onboarding properties filter

- src/extend/template-selector/templateContext.js
> Fix: Template selector missing inspector controls

- includes/blocks/class-button.php
- readme.txt
> Fix: Dynamic button tag name

- src/components/dimensions/editor.scss
- src/components/dimensions/index.js
> Tweak: Force lowercase margin value

- includes/blocks/class-button.php
- includes/class-dynamic-content.php
- readme.txt
Replace the `gb-button__current` class with a generic `gb-block-is-current` class.
> Tweak: Replace gb-button__current class with gb-block-is-current

- src/extend/inspector-control/index.js
This moves the Colors panel down so we can have "zones" based on what each panel does.
> Tweak: Re-order panels

- src/blocks/grid/components/LayoutSelector.js
> Fix: Grid columns dont have width set correctly

- includes/blocks/class-container.php
- readme.txt
- src/blocks/container/css/main.js
> Fix: Add pointer-events to pseudo background

- src/extend/inspector-control/controls/layout/index.js
Add "EM" to the layout column/row gap.
> Feat: Add EM to column/row gaps

- src/extend/inspector-control/controls/layout/components/FlexDirection.js
- src/extend/inspector-control/controls/layout/components/LayoutControl.js
- src/extend/inspector-control/controls/layout/index.js
- src/shared/editor.scss
> Tweak: Show inherited highlight in layout buttons

- src/extend/inspector-control/controls/responsive-tabs/index.js
> Fix: Missing device buttons when using multi-select

- includes/class-dynamic-content.php
- readme.txt
> Fix: Triple captions using static image with dynamic link

- src/components/migrate-inner-container/index.js
- src/components/migrate-inner-container/utils.js
Fixes an error when migrating Containers if GB Pro isn't activated.
> Fix: Container migration error

- includes/class-enqueue-css.php
This fixes a bug where our blocks lose their styling in block theme templates.
> Fix: Block styling in block theme templates

- includes/class-enqueue-css.php
- includes/general.php
- package.json
- plugin.php
- readme.txt
> Release: 1.7.2

- includes/blocks/class-button.php
> Fix: Button with dynamic content not displaying the aria-label

- src/blocks/container/attributes.js
- src/blocks/container/components/ContainerContentRenderer.js
- src/blocks/grid/attributes.js
- src/blocks/grid/edit.js
> Fix: Template lock system not applying to inner  blocks

- src/hoc/test/withUniqueId.test.js
- src/utils/get-editor-blocks.js
> Fix: unique id not regenareted correctly on widgets editor

- src/blocks/headline/block.js
> Feat: Headline block show hint text in List View

- src/extend/inspector-control/index.js
> Fix: Color and Background panels are visible/accessible on Responsive views

- .distignore
- .github/workflows/ci.yml
- .gitignore
- composer.json
- phpcs.xml.dist
- phpunit.xml
- tests/bootstrap.php
- tests/unit/DynamicCSSTest.php
> Chore: Add PHP tests

- src/blocks/button/block.js
- src/blocks/container/attributes.js
- src/blocks/container/block.js
- src/blocks/container/components/InspectorAdvancedControls.js
- src/blocks/image/index.js
Add custom labels for the blocks on the list view.
> Feature: Add block labels to the list view

- src/blocks/query-loop/editor.scss
> Fix: Query loop parameter delete button size

- includes/blocks/class-button.php
- includes/blocks/class-headline.php
- includes/class-map-deprecated-attributes.php
- includes/functions.php
- tests/Unit/MapDeprecatedAttributesTest.php
- tests/unit/DynamicCSSTest.php
This adds our old typography attributes to our mapping class and adds a few more tests.
> Tweak: Map old typography attributes

- includes/functions.php
- src/components/icon-picker/index.js
- src/hoc/migrations/migrateBorders.js
- src/hoc/migrations/migrateIconPadding.js
- src/hoc/migrations/migrateSizing.js
- src/hoc/migrations/migrateSpacing.js
- src/hoc/migrations/migrateTypography.js
- src/hoc/migrations/migratingIconSizing.js
- src/hoc/withButtonContainerLegacyMigration.js
- src/hoc/withButtonLegacyMigration.js
- src/hoc/withContainerLegacyMigration.js
- src/hoc/withGridLegacyMigration.js
- src/hoc/withHeadlineLegacyMigration.js
- src/hoc/withImageLegacyMigration.js
- src/tests/unit/migrations/defaults.js
- src/tests/unit/migrations/migrateBorders.test.js
- src/tests/unit/migrations/migrateIconSizing.test.js
- src/tests/unit/migrations/migrateSpacing.test.js
- src/tests/unit/migrations/migrateTypography.test.js
- src/tests/unit/migrations/withButtonContainerMigration.test.js
- src/tests/unit/migrations/withButtonMigration.test.js
- src/tests/unit/migrations/withContainerMigration.test.js
- src/tests/unit/migrations/withGridMigration.test.js
- src/tests/unit/migrations/withHeadlineMigration.test.js
- src/tests/unit/migrations/withImageMigration.test.js
- tests/unit/DynamicCSSTest.php
Adds more tests and fixes a handful of bugs found while testing.
> Chore: Add more migration tests

- src/blocks/container/components/BlockControls.js
> Tweak: Keep Container text align option when using flex

- src/components/dimensions/index.js
This makes it so only one dimension field displays if all 4 sides are synced.
> Feature: Only show one dimension field if synced

- src/hooks/useDeviceType.js
> Fix: useDeviceType state was one state behind when triggered from core buttons

- src/components/unit-control/index.js
> Fix: Allow negative value number in `UnitControl`

- src/components/unit-control/index.js
This removes the preset feature in the `UnitControl` component as we don't use it anywhere and have no plans to use it.
> Tweak: Clean up `UnitControl`

- readme.txt
- src/blocks/query-loop/editor.scss
> Tweak: Remove top/bottom margin from Query Loop in the editor

- src/components/dimensions/editor.scss
- src/components/dimensions/index.js
- src/components/dimensions/labels.js
- src/extend/inspector-control/controls/borders/index.js
- src/extend/inspector-control/controls/spacing/index.js
> Fix: Logical tabbing order of `Dimensions` component

- includes/functions.php
- readme.txt
https://make.wordpress.org/core/2023/07/13/image-performance-enhancements-in-wordpress-6-3/
> Tweak: Add support for the newly created core function "wp_img_tag_add_loading_optimization_attrs"

- includes/pattern-library/class-libraries.php
- includes/pattern-library/class-pattern-library-rest.php
- package-lock.json
- package.json
- src/blocks/pattern-library/components/category-list.js
- src/blocks/pattern-library/components/library-cache.js
- src/blocks/pattern-library/components/library-pagination.js
- src/blocks/pattern-library/components/library-provider.js
- src/blocks/pattern-library/components/pattern-list.js
- src/blocks/pattern-library/components/pattern-search.js
- src/blocks/pattern-library/editor.scss
This PR adds caching to our remote libraries.
It also adds pagination to the library and improves overall loading performance.
> Feature: Add library caching

- src/components/unit-control/index.js
Fixes #1135.
This PR is based on the release branch rather than the pattern branch so should be safe to merge. Closing PR #1145 in favor of this one.
> Add support for using up/down cursor keys to change numerical input values

- src/components/color-picker/index.js
- src/components/icon-picker/index.js
- src/components/unit-picker/index.js
> Fixed some dep. notices

- includes/class-dynamic-content.php
This escapes data being output in a custom field dynamic data type.
> Security: Disallow scripts in custom field values

- includes/functions.php
> Fix: Wrong const

- src/pattern-library/components/pattern-details.js
- src/pattern-library/components/selected-patterns.js
- src/pattern-library/utils.js
closes https://github.com/tomusborne/generateblocks-pro/issues/472
> Tweak: Regenerate `uniqueId` on pattern insertion

- src/pattern-library/components/category-list.js
- src/pattern-library/components/library-layout.js
- src/pattern-library/components/pattern-list.js
- src/pattern-library/editor.scss
This PR tweaks the bulk insert UI in the pattern library.
1. Moved the bulk insert button above where the selected patterns go
2. Collapse the categories in a dropdown menu when selected patterns exist
3. Improved UI of selected pattern border/icons
> Tweak: Bulk insert UI

- includes/pattern-library/class-libraries.php
- src/pattern-library/components/library-provider.js
This opens the "Pro" pattern library by default when you open the pattern library if it exists.
Otherwise it will default to the first library.
> Tweak: Open Pro library by default if it exists

- includes/functions.php
- src/dashboard.js
This adds a new `desktop_tablet` media query.
> Tweak: Add new media query

- src/components/unit-control/index.js
Fixes issue that caused the Layout width buttons to not work as expected.
> Grid Block - Fix Layout button issue 

- src/blocks/headline/editor.scss
> Fix: Unsetting of headline margin

- includes/pattern-library/class-libraries.php
- src/pattern-library/components/library-provider.js
This allows us to specify a pattern category to open by default.
> Feature: Add filter to open pattern category by default

- includes/general.php
- src/extend/inspector-control/controls/sizing/index.js
- src/utils/get-variable-value/index.js
This adds a new `--gb-container-width` CSS variable for our global max-width option.
> Feature: Use CSS variable for global max-width

- package-lock.json
- src/dashboard.scss
This PR adds scroll behavior to the header on mobile so all of the nav items can be seen. 
https://github.com/tomusborne/generateblocks/assets/11017412/ddd57cef-6e67-4d87-b9b7-ef1b07d4578a
> Improve dashboard header on mobile

- includes/class-dynamic-content.php
Fixes deprecation error for class-dynamic-content.php
> Fix php trim warning

- src/blocks/text/block.json
- src/blocks/text/components/BlockSettings.jsx
- src/blocks/text/edit.js
- src/blocks/text/save.js
This adds the ability to only show the icon inside of the Text block.
> Feature: Add "icon only" option to Text block

- src/blocks/element/block.json
This PR allows list tag names in the Element block.
> Feature: Allow list tag names

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
- includes/dynamic-tags/class-register-dynamic-tag.php
- src/blocks/query/templates.js
- src/blocks/text/components/DynamicTag.jsx
- src/blocks/text/edit.js
- src/dynamic-tags/components/DynamicTagBlockToolbar.jsx
- src/dynamic-tags/components/DynamicTagModal.jsx
- src/dynamic-tags/components/DynamicTagSelect.jsx
- src/dynamic-tags/components/SelectPost.jsx
If you select an existing tag in the editor, this PR will:
1. Highlight the dynamic tag button in the toolbar
2. Parse the tag and its options to fill out the fields in the modal
> Feature: Parse selected tag

- src/components/html-attributes/HtmlAttributes.jsx
A small change that should improve the HTML attributes component UX.
> Tweak: Improve HTML attributes component

- includes/class-rest.php
- src/blocks/media/components/BlockSettings.jsx
This adds an Image Size dropdown to the new Image block.
> Feature: Add Image Size feature to image block

- src/pattern-library/components/library-layout.js
> Fix: Special characters in pattern preview title

- src/extend/inspector-control/controls/responsive-tabs/index.js
> Fix: Sticky responsive tabs

- includes/general.php
- package-lock.json
- package.json
- webpack.config.js
Fix issue with package deps, same as in pro
> Fix package deps for edge22 packages

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
- includes/dynamic-tags/class-dynamic-tags.php
> Add post excerpt, minor bug fix for filters

- package-lock.json
- package.json
- src/hoc/withStyles.js
Replaces https://github.com/tomusborne/generateblocks/pull/1323
> Tweak: Sync styles attribute and store

- src/components/image-upload/ImageUpload.jsx
- src/dynamic-tags/components/DynamicTagModal.jsx
> Fix: Broken dynamic background image

- includes/blocks/class-query.php
- src/blocks/query/looper.js
- src/blocks/query/templates.js
> Fix: Broken query pagination

- src/blocks/text/edit.js
> Tweak: Disable dynamic tag links in the editor

- src/blocks/text/components/BlockSettings.jsx
- src/blocks/text/edit.js
This improves the UI around the icon feature in the Text block.
* Adds an icon color shortcut
* Removes the dynamic tag option in the toolbar if text is removed from the text block (icon-only)
> Tweak: Improve text icon UI

- src/components/image-upload/ImageUpload.jsx
- src/components/url-controls/URLControls.jsx
This pre-fills the dynamic tag data in the modal if opening the modal from an input (URL/image controls).
> Tweak: Pre-fill dynamic tag data from inputs

- src/blocks/media/index.js
- src/blocks/media/transforms.js
- src/blocks/text/index.js
- src/blocks/text/transforms.js
This PR adds basic block transforms between core blocks and our v2 blocks.
> Feature: Add basic block transforms

- plugin.php
Reference: https://core.trac.wordpress.org/ticket/44937
> Fix: Text domain load order

- src/blocks/button/transforms.js
- src/blocks/container/block.js
- src/blocks/container/transforms.js
- src/blocks/element/block.json
- src/blocks/element/index.js
- src/blocks/headline/transforms.js
- src/blocks/image/transforms.js
- src/blocks/media/block.json
- src/blocks/text/index.js
- src/utils/convertLegacyHtmlAttributes.js
This adds more block transforms from v1 to v2 blocks.
> Tweak: Add more block transforms

- package-lock.json
- package.json
> Fix: Selector delete runtime error

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
Fixes #1386
Added missing params for priority and arg count.
> Bug - Author Meta meta_object filter hook params

- src/blocks/media/block.json
- src/blocks/media/index.js
> Add default styles to the Image block variation

- src/pattern-library/components/pattern.js
Related: https://github.com/tomusborne/generateblocks-pro/pull/729
> Tweak: Add stylesheet support to pattern previews

- includes/blocks/class-looper.php
- includes/class-meta-handler.php
- includes/dynamic-tags/class-dynamic-tag-callbacks.php
- includes/dynamic-tags/class-dynamic-tags.php
closes #1390 
This PR fixes a couple of bugs and adds a new author avatar URL dynamic tag.
> Feature: Add author avatar url tag

- src/components/template-selector/TemplateSelector.jsx
- src/components/template-selector/editor.scss
> Fix: Variation selector layout

- package-lock.json
- package.json
- src/blocks/text/components/BlockSettings.jsx
This updates the Icon Library component and improves some of the default styling when setting an icon.
> Tweak: Improve icon presets

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
> Dynamic Tag - Fix post excerpt useTheme  setting

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
- includes/dynamic-tags/class-dynamic-tags.php
Removed these in #1413, but it looks like we use them in the Query templates in free.
> Tweak: Add next/previous post URL tags

- package-lock.json
- package.json
- src/blocks/media/components/BlockSettings.jsx
- src/blocks/shape/components/BlockSettings.jsx
https://github.com/EDGE22-Studios/styles-builder/pull/10
> Tweak: Update styles builder

- src/blocks/media/edit.js
- src/blocks/media/index.js
- src/blocks/media/toolbar-appenders.js
- src/blocks/query/edit.js
- src/blocks/query/index.js
- src/blocks/query/toolbar-appenders.js
- src/editor/index.js
- src/editor/toolbar-appenders.js
- src/settings.scss
This PR makes it so all of our toolbar appenders live in a single toolbar group.
> Refactor: Toolbar appenders

- includes/class-dynamic-content.php
- includes/functions.php
This removes a function that ended up never being used, as well as a variable.
> Refacto: Remove unused function

- package-lock.json
- package.json
- src/editor/global-max-width.js
- src/editor/index.js
This adds the global max-width button to the max-width field.
Requires https://github.com/EDGE22-Studios/styles-builder/pull/13
> Feature: Add global max-width button

- src/blocks/media/components/BlockSettings.jsx
- src/blocks/media/index.js
Some minor tweaks, adds width as a new default value for the image block, adds Controls to the Block settings, fixed an uncontrolled component.
> Image Block Settings Update

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
- includes/dynamic-tags/class-dynamic-tags.php
- src/blocks/element/components/BlockSettings.jsx
- src/blocks/loop-item/components/BlockSettings.jsx
- src/blocks/media/components/BlockSettings.jsx
- src/blocks/text/components/BlockSettings.jsx
- src/components/link-block-toolbar/LinkBlockToolbar.jsx
- src/components/url-controls/URLControls.jsx
- src/dynamic-tags/components/DynamicTagSelect.jsx
Adds mechanism to make dynamic tags visible or hidden based on the value of a supported block attribute. Currently only tagName is supported.
> Dynamic Tags - Block attribute visibility

- src/blocks/query/components/QueryInspectorControls.jsx
> Tweak: Hide single Query Type

- includes/blocks/class-looper.php
> Fix: Allow multiple inner blocks inside the Looper

- package-lock.json
- package.json
- src/hoc/withStyles.js
context: https://github.com/EDGE22-Studios/block-styles/pull/11
> Tweak: Use `useSetStyles`

- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
> Fix: Query posts_per_page when set to -1

- package-lock.json
- package.json
* Fix: GridTemplateColumns debounce
* New: Add `cursor` control
* Tweak: Move `fontWeight` below `fontSize`
> Update styles builder

- includes/class-query-utils.php
Minor tweaks and fixes for query loop
> Remove unused function, fix stickyPost unset

- src/blocks/query-page-numbers/block.json
> Fix query loop paging link issue

- package-lock.json
- package.json
This fixes the color picker width when a lot of palette options exist.
> Fix: Color picker width

- package-lock.json
- package.json
- src/hoc/withStyles.js
Requires linking to https://github.com/EDGE22-Studios/block-styles/pull/12
> Refactor: Editor styles

- includes/general.php
- package-lock.json
- package.json
Fixes #1449
Requires: https://github.com/EDGE22-Studios/styles-builder/pull/27
> BG Placeholder handling

- src/blocks/shape/components/BlockSettings.jsx
- src/blocks/shape/components/ShapeDividerControls.jsx
closes #1542 
https://github.com/user-attachments/assets/577898ee-5bf4-4933-907d-6350064e0f1f
> Feature: Add shape divider position options

- src/blocks/query/toolbar-appenders.js
- src/utils/getInnerBlocks.js
- src/utils/index.js
> Query - Update pagination and no results buttons

- src/blocks/shape/index.js
- src/blocks/text/components/BlockSettings.jsx
> Icon & Shapes - set fill color by default

- includes/dynamic-tags/class-dynamic-tags.php
Replaces https://github.com/tomusborne/generateblocks/pull/1570
> Fix: Taxonomy term dynamic tags

- includes/class-meta-handler.php
Closes: https://github.com/tomusborne/generateblocks-pro/issues/770
> Meta Handler - add support for non-single meta

- package-lock.json
- package.json
- src/blocks/query/templates.js
Closes #1580  Adds responsive styles and image containment styles. 
Requires: https://github.com/EDGE22-Studios/styles-builder/pull/33
> Query - Update responsive styles in templates

- package-lock.json
- package.json
- src/blocks/element/index.js
- src/utils/mobileAtRule.jsx
This PR makes our Grid block variation responsive by default, and adds some default grid gap.
> Tweak: Add responsive grid defaults

- src/blocks/loop-item/block.json
- src/blocks/loop-item/edit.js
- src/blocks/loop-item/editor.scss
- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
closes https://github.com/tomusborne/generateblocks-pro/issues/796
> Fix: Loop item bugs

- src/blocks/loop-item/components/BlockSettings.jsx
closes https://github.com/tomusborne/generateblocks-pro/issues/797
> Feature: Add inline background control to Loop Item

- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
closes https://github.com/tomusborne/generateblocks-pro/issues/798
> Tweak: Show Looper appender if empty

- package-lock.json
- package.json
* float
* clear
* align-self
* justify-items
* justify-self
> Feature: Add more CSS properties

- src/dynamic-tags/components/DynamicTagSelect.jsx
Fixes an issue that caused the DynamicTagSelect to display incorrect UI due to additional unnecessary state updates.
> Fix bug with dynamic tag data state

- includes/general.php
> Fix: Default button styling

- src/pattern-library/components/category-list.js
closes https://github.com/tomusborne/generateblocks/issues/1620
alternative to https://github.com/tomusborne/generateblocks/pull/1624
> Fix: HTML entities in pattern category names

- src/editor/style-html-attribute.js
Fixes an issue mentioned here: https://github.com/tomusborne/generateblocks/issues/1613#issuecomment-2567555165
> Fix: Inline dynamic bgs

- package-lock.json
- package.json
related: https://github.com/EDGE22-Studios/styles-builder/pull/43
closes https://github.com/tomusborne/generateblocks/issues/1642
> Fix: Styles builder values getting mixed up

- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
> Fix: Editor offset with limited posts

- package-lock.json
- package.json
* Fix: Missing horizontal search
* Fix: Indicator dots
* Fix: Image URL sizing
> Packages: Update styles builder

- package-lock.json
- package.json
- src/utils/legacyStyleUtils.js
related https://github.com/EDGE22-Studios/styles-builder/pull/51
This also sneaks in a fix for block transforms.
> Refactor: Improve Layout panel UI

- src/blocks/button/transforms.js
- src/utils/legacyStyleUtils.js
> Fix: Block transform bugs

- src/blocks/element/block.json
- src/blocks/element/editor.scss
> Tweak: Add box-sizing to container

- src/blocks/grid/transforms.js
> Improve: Grid transforms

- package-lock.json
- package.json
- src/components/block-styles-builder/BlockStylesBuilder.jsx
related https://github.com/EDGE22-Studios/styles-builder/pull/53
> Tweak: Add computed style deps to Styles Builder

- includes/general.php
> Fix: Allow Element and Text blocks in excerpts

- src/blocks/media/edit.js
closes https://github.com/tomusborne/generateblocks-pro/issues/826
> Fix: Multi-selecting image block

- includes/dynamic-tags/class-dynamic-tag-callbacks.php
This prevents possible infinite loops when using the post excerpt tag.
> Fix: Post excerpt possible infinite loop

- package-lock.json
- package.json
Context: https://github.com/EDGE22-Studios/styles-builder/pull/59
> Fix: Hover style indicators display

- package-lock.json
- package.json
closes #1667 
context: https://github.com/EDGE22-Studios/block-styles/pull/19
> Fix: Unique ID regeneration

- includes/blocks/class-loop-item.php
- includes/blocks/class-looper.php
This PR fixes a potential memory leak when dealing with large datasets and nested queries.
> Fix: Query data memory usage

- src/blocks/loop-item/block.json
- src/blocks/loop-item/edit.js
- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Update previewId and context handling
> Query Preview fixes

- package-lock.json
- package.json
context https://github.com/EDGE22-Studios/styles-builder/pull/63
> Fix: Allow empty gradient stops

- src/blocks/headline/transforms.js
> Fix: Undefined content on Headline transform

- src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
> Fix: Query re-rendering on auto-save

- package-lock.json
- package.json
Context: https://github.com/EDGE22-Studios/styles-builder/pull/65
> Tweak: Validate CSS values on input blur

- package-lock.json
- package.json
context https://github.com/EDGE22-Studios/styles-builder/pull/68
> Fix: Radial gradients

- src/blocks/text/components/BlockSettings.jsx
- src/hoc/withHtmlAttributes.js
closes https://github.com/tomusborne/generateblocks/issues/1787
> Feature: Add `aria-label` option to all blocks

- package-lock.json
- package.json
related https://github.com/EDGE22-Studios/block-styles/pull/23
> Fix: Block preview styles

- package-lock.json
- package.json
* Tweak: Improve editor performance https://github.com/EDGE22-Studios/styles-builder/pull/73
* Feature: Add `inline-grid` option https://github.com/EDGE22-Studios/styles-builder/pull/74
> Update: Styles Builder

- package-lock.json
- package.json
- src/blocks/element/components/BlockSettings.jsx
- src/blocks/loop-item/components/BlockSettings.jsx
- src/blocks/looper/components/BlockSettings.jsx
- src/blocks/media/components/BlockSettings.jsx
- src/blocks/query-page-numbers/components/BlockSettings.jsx
- src/blocks/query/components/BlockSettings.jsx
- src/blocks/shape/components/BlockSettings.jsx
- src/blocks/text/components/BlockSettings.jsx
This adds support for this feature: https://github.com/tomusborne/generateblocks-pro/pull/861
> Feature: Add support for device visibility feature

- package-lock.json
- package.json
- src/components/block-styles-builder/BlockStylesBuilder.jsx
related https://github.com/EDGE22-Studios/styles-builder/pull/75
> Feature: Improve indicator dot system

- package-lock.json
- package.json
- src/blocks/element/edit.js
- src/blocks/loop-item/edit.js
- src/blocks/looper/edit.js
- src/blocks/query-page-numbers/edit.js
- src/blocks/query/edit.js
- src/blocks/shape/edit.js
- src/blocks/text/edit.js
- src/components/block-styles-builder/BlockStylesBuilder.jsx
This updates the default selectors in the styles builder to make them more consistent.
> Tweak: Default block selectors

- package-lock.json
- package.json
context https://github.com/EDGE22-Studios/styles-builder/pull/80
> Fix: Indicator dot shortcuts

- includes/class-meta-handler.php
- readme.txt
closes https://github.com/tomusborne/generateblocks/issues/1832
> Fix: Allow `0` as post meta key

- package-lock.json
- package.json
* Fix: Regen CSS when styles are empty https://github.com/EDGE22-Studios/block-styles/pull/27
> Update: Block Styles
